### ISSUE TITLE
Rt plot showing really high values initially, masking the smaller values afterwards

### ISSUE THREAD

**Issue by SaiTheinThanTun** [ocelhay/como#16]
![image](https://user-images.githubusercontent.com/7494927/79973076-ee014480-84bc-11ea-9ffc-6223f54109df.png)
Result associated with these parameters: 
[highest intervention.xlsx](https://github.com/ocelhay/como/files/4515585/highest.intervention.xlsx)

**Comment by ocelhay** [comment]
@ricardoaguas is testing to find how many values at the start could be removed from the plot.

**Comment by ocelhay** [comment]
The Rt above 7 are normalised.
