### ISSUE TITLE
Working at home and school closure intervention parameter dialog options get cut-off at the top

### ISSUE THREAD

**Issue by ernestguevarra** [ocelhay/como#4]
Issue reported by Ainura on Slack (https://covid19-crew.slack.com/archives/CVDMWRM1Q/p1586868719233600).

Replicated the issue via the online app using a 17" MacBook Pro with browser showing on full screen. I was able to replicate the first part of the issue which is the working at home dialog options getting covered by the navigation bar on top (see screenshot below) but not for school closure.

<img width="1552" alt="Screenshot 2020-04-14 at 13 54 34" src="https://user-images.githubusercontent.com/5742010/79228021-b65d2180-7e58-11ea-8150-d49cb5b80b04.png">

This may indicate that this is screen size dependent that I am sure can be tweaked easily either via re-sizing the dialog options elements and/or re-configuring shinyBS options (??)

**Comment by ocelhay** [comment]
A possibility is to have these parameters in two columns. Another option would be to regroup all interventions parameters in a slider window (similar to the ones appearing when clicking on the Country/Virus/Hospital buttons).

**Comment by ocelhay** [comment]
Interventions parameters are grouped into a slider window.
